version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "yearly"
    groups:
      spring-boot:
        patterns:
          - "spring-boot-*"
      kotlin:
        patterns:
          - "kotlin-*"
      jackson:
        patterns:
          - "jackson-*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "yearly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "yearly"
